registry:
  server: ghcr.io
  org: youndie

hostname: ""

server:
  image: katcher
  version: 0.2.2.993
  resources:
    requests:
      cpu: "30m"
      memory: "32Mi"
    limits:
      cpu: "1"
      memory: "64Mi"

db:
  size: 512Mi
  class: "local-path"
  path: /data
  name: local.db

sourceMaps:
  size: 2Gi
  class: "local-path"
  path: /source-maps

traefik:
  certResolver: cloudflare
  authMiddleware:
    name: ""
    namespace: ""
  middlewares: []
