apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlite-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    app: katcher-backend
spec:
  storageClassName: {{ .Values.db.class | quote }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.db.size | quote }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mappings-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    app: katcher-backend
spec:
  storageClassName: {{ .Values.sourceMaps.class | quote }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.sourceMaps.size | quote }}
