apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlite-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    app: katcher-backend
spec:
  storageClassName: {{ .Values.storage.class | quote }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size | quote }}
